site_name: urbanity

site_url: https://winstonyym.github.io/urbanity

repo_url: https://github.com/winstonyym/urbanity

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocs-jupyter
          
markdown_extensions:
    - attr_list
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/winstonyym/urbanity/issues
    - API Reference:
          - urbanity : urbanity.md
          - urbanity more: urbanity_more.md
    - Notebooks: apple.ipynb
